# Generated by Django 5.0.2 on 2024-03-11 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignIn',
        ),
    ]
